version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-app-1
      - spring-app-2
      - spring-app-3
      - postgres


  spring-app-1:
    image: benchmarking-postgres
    depends_on:
      - postgres


  spring-app-2:
    image: benchmarking-postgres
    depends_on:
      - postgres



  spring-app-3:
    image: benchmarking-postgres
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: session_benchmarking


