version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-app-1
      - spring-app-2
      - spring-app-3
      - redis

  spring-app-1:
    image: benchmarking-redis
    depends_on:
      - redis

  spring-app-2:
    image: benchmarking-redis
    depends_on:
      - redis


  spring-app-3:
    image: benchmarking-redis
    depends_on:
      - redis


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

